# Generated by Django 5.1.7 on 2025-04-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_category_enrollment_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
