# Generated by Django 5.1.7 on 2025-04-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.TextField(blank=True, help_text='Материалы урока (например, теория)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='solution',
            field=models.TextField(blank=True, help_text='Правильное решение (скрыто от пользователя)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='task',
            field=models.TextField(blank=True, help_text='Задание для пользователя'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Дополнительные заметки к уроку (опционально)'),
        ),
    ]
